
STUDENT_MODELS = {
	-- Male
	[1] = {
		[1] = "models/Humans/Group01/Male_01.mdl",
		[2] = "models/Humans/Group01/male_02.mdl",
		[3] = "models/Humans/Group01/male_03.mdl",
		[4] = "models/Humans/Group01/Male_04.mdl",
		[5] = "models/Humans/Group01/Male_05.mdl",
		[6] = "models/Humans/Group01/male_06.mdl",
		[7] = "models/Humans/Group01/male_07.mdl",
		[8] = "models/Humans/Group01/male_09.mdl",
	},
	-- Female
	[2] = {
		[1] = "models/Humans/Group01/Female_01.mdl",
		[2] = "models/Humans/Group01/Female_02.mdl",
		[3] = "models/Humans/Group01/Female_03.mdl",
		[4] = "models/Humans/Group01/Female_04.mdl",
		[5] = "models/Humans/Group01/Female_06.mdl",
		[6] = "models/Humans/Group01/Female_07.mdl",
	},
}

STUDENT_PLAYER_MODELS = {
	-- Male
	[1] = {
		[1] = "models/player/Group01/Male_01.mdl",
		[2] = "models/player/Group01/male_02.mdl",
		[3] = "models/player/Group01/male_03.mdl",
		[4] = "models/player/Group01/Male_04.mdl",
		[5] = "models/player/Group01/Male_05.mdl",
		[6] = "models/player/Group01/male_06.mdl",
		[7] = "models/player/Group01/male_07.mdl",
		[8] = "models/player/Group01/male_09.mdl",
	},
	-- Female
	[2] = {
		[1] = "models/player/Group01/Female_01.mdl",
		[2] = "models/player/Group01/Female_02.mdl",
		[3] = "models/player/Group01/Female_03.mdl",
		[4] = "models/player/Group01/Female_04.mdl",
		[5] = "models/player/Group01/Female_06.mdl",
	},
}

if SERVER then
	TEACHER_NAMES = {
		"Smith",
		"Johnson",
		"Williams",
		"Jones",
		"Brown",
		"Davis",
		"Miller",
		"Wilson",
		"Moore",
		"Taylor",
		"Anderson",
		"Thomas",
		"Jackson",
		"White",
		"Harris",
		"Martin",
		"Thompson",
		"Garcia",
		"Martinez",
		"Robinson",
		"Clark",
		"Rodriguez",
		"Lewis",
		"Lee",
		"Walker",
		"Hall",
		"Allen",
		"Young",
		"Hernandez",
		"King",
		"Wright",
		"Lopez",
		"Hill",
		"Scott",
		"Green",
		"Adams",
		"Baker",
		"Gonzalez",
		"Nelson",
		"Carter",
		"Mitchell",
		"Perez",
		"Roberts",
		"Turner",
		"Phillips",
		"Campbell",
		"Parker",
		"Evans",
		"Edwards",
		"Collins",
		"Stewart",
		"Sanchez",
		"Morris",
		"Rogers",
		"Reed",
		"Cook",
		"Morgan",
		"Bell",
		"Murphy",
		"Bailey",
		"Rivera",
		"Cooper",
		"Richardson",
		"Cox",
		"Howard",
		"Ward",
		"Torres",
		"Peterson",
		"Gray",
		"Ramirez",
		"James",
		"Watson",
		"Brooks",
		"Kelly",
		"Sanders",
		"Price",
		"Bennett",
		"Wood",
		"Barnes",
		"Ross",
		"Henderson",
		"Coleman",
		"Jenkins",
		"Perry",
		"Powell",
		"Long",
		"Patterson",
		"Hughes",
		"Flores",
		"Washington",
		"Butler",
		"Simmons",
		"Foster",
		"Gonzales",
		"Bryant",
		"Alexander",
		"Russell",
		"Griffin",
		"Diaz",
		"Hayes",
		"Myers",
		"Ford",
		"Hamilton",
		"Graham",
		"Sullivan",
		"Wallace",
		"Woods",
		"Cole",
		"West",
		"Jordan",
		"Owens",
		"Reynolds",
		"Fisher",
		"Ellis",
		"Harrison",
		"Gibson",
		"Mcdonald",
		"Cruz",
		"Marshall",
		"Ortiz",
		"Gomez",
		"Murray",
		"Freeman",
		"Wells",
		"Webb",
		"Simpson",
		"Stevens",
		"Tucker",
		"Porter",
		"Hunter",
		"Hicks",
		"Crawford",
		"Henry",
		"Boyd",
		"Mason",
		"Morales",
		"Kennedy",
		"Warren",
		"Dixon",
		"Ramos",
		"Reyes",
		"Burns",
		"Gordon",
		"Shaw",
		"Holmes",
		"Rice",
		"Robertson",
		"Hunt",
		"Black",
		"Daniels",
		"Palmer",
		"Mills",
		"Nichols",
		"Grant",
		"Knight",
		"Ferguson",
		"Rose",
		"Stone",
		"Hawkins",
		"Dunn",
		"Perkins",
		"Hudson",
		"Spencer",
		"Gardner",
		"Stephens",
		"Payne",
		"Pierce",
		"Berry",
		"Matthews",
		"Arnold",
		"Wagner",
		"Willis",
		"Ray",
		"Watkins",
		"Olson",
		"Carroll",
		"Duncan",
		"Snyder",
		"Hart",
		"Cunningham",
		"Bradley",
		"Lane",
		"Andrews",
		"Ruiz",
		"Harper",
		"Fox",
		"Riley",
		"Armstrong",
		"Carpenter",
		"Weaver",
		"Greene",
		"Lawrence",
		"Elliott",
		"Chavez",
		"Sims",
		"Austin",
		"Peters",
		"Kelley",
		"Franklin",
		"Lawson",
		"Fields",
		"Gutierrez",
		"Ryan",
		"Schmidt",
		"Carr",
		"Vasquez",
		"Castillo",
		"Wheeler",
		"Chapman",
		"Oliver",
		"Montgomery",
		"Richards",
		"Williamson",
		"Johnston",
		"Banks",
		"Meyer",
		"Bishop",
		"Mccoy",
		"Howell",
		"Alvarez",
		"Morrison",
		"Hansen",
		"Fernandez",
		"Garza",
		"Harvey",
		"Little",
		"Burton",
		"Stanley",
		"Nguyen",
		"George",
		"Jacobs",
		"Reid",
		"Kim",
		"Fuller",
		"Lynch",
		"Dean",
		"Gilbert",
		"Garrett",
		"Romero",
		"Welch",
		"Larson",
		"Frazier",
		"Burke",
		"Hanson",
		"Day",
		"Mendoza",
		"Moreno",
		"Bowman",
		"Medina",
		"Fowler",
		"Brewer",
		"Hoffman",
		"Carlson",
		"Silva",
		"Pearson",
		"Holland",
		"Douglas",
		"Fleming",
		"Jensen",
		"Vargas",
		"Byrd",
		"Davidson",
		"Hopkins",
		"May",
		"Terry",
		"Herrera",
		"Wade",
		"Soto",
		"Walters",
		"Curtis",
		"Neal",
		"Caldwell",
		"Lowe",
		"Jennings",
		"Barnett",
		"Graves",
		"Jimenez",
		"Horton",
		"Shelton",
		"Barrett",
		"brien",
		"Castro",
		"Sutton",
		"Gregory",
		"Mckinney",
		"Lucas",
		"Miles",
		"Craig",
		"Rodriquez",
		"Chambers",
		"Holt",
		"Lambert",
		"Fletcher",
		"Watts",
		"Bates",
		"Hale",
		"Rhodes",
		"Pena",
		"Beck",
		"Newman",
		"Haynes",
		"Mcdaniel",
		"Mendez",
		"Bush",
		"Vaughn",
		"Parks",
		"Dawson",
		"Santiago",
		"Norris",
		"Hardy",
		"Love",
		"Steele",
		"Curry",
		"Powers",
		"Schultz",
		"Barker",
		"Guzman",
		"Page",
		"Munoz",
		"Ball",
		"Keller",
		"Chandler",
		"Weber",
		"Leonard",
		"Walsh",
		"Lyons",
		"Ramsey",
		"Wolfe",
		"Schneider",
		"Mullins",
		"Benson",
		"Sharp",
		"Bowen",
		"Daniel",
		"Barber",
		"Cummings",
		"Hines",
		"Baldwin",
		"Griffith",
		"Valdez",
		"Hubbard",
		"Salazar",
		"Reeves",
		"Warner",
		"Stevenson",
		"Burgess",
		"Santos",
		"Tate",
		"Cross",
		"Garner",
	}

	MALE_NAMES = {
		"Riley",
		"Federico",
		"Rhys",
		"Reyes",
		"Niko",
		"Neil",
		"Kerr",
		"Jeb",
		"Geoffrey",
		"Jeff",
		"Mike",
		"Michael",
		"Micah",
		"Cliff",
		"Clifford",
		"Greg",
		"Gregory",
		"Aaron",
		"Danny",
		"Charlie",
		"Westley",
		"Geoff",
		"Chad",
		"Chandler",
		"Rylan",
		"Rhett",
		"Max",
		"Paul",
		"Paulie",
		"Jaden",
		"Kyler",
		"Guy",
		"Landed",
		"Elroy",
		"Morris",
		"Ashton",
		"Dallas",
		"Will",
		"William",
		"Sebastion",
		"Hector",
		"Chris",
		"Christian",
		"Christopher",
		"Braden",
		"Parker",
		"Henry",
		"Darius",
		"Red",
		"Osmond",
		"Holden",
		"Olson",
		"Josh",
		"Joshua",
		"Joshie",
		"Stephen",
		"Steven",
		"Steve",
		"Steph",
		"Cory",
		"Duncan",
		"Simon",
		"Lewis",
		"Orval",
		"Orel",
		"Tod",
		"Todd",
		"Topher",
		"Kyle",
		"Kyler",
		"Bradley",
		"Eben",
		"Jim",
		"James",
		"John",
		"Jon",
		"Jonathan",
		"Joe",
		"LJ",
		"AJ",
		"RJ",
		"DJ",
		"Dee",
		"Taylor",
		"Dalton",
		"Daedae",
		"Rafferty",
		"Clint",
		"Clinton",
		"Kim",
		"Henry",
		"Stew",
		"Stewart",
		"Stewie",
		"Upton",
		"Harvey",
		"Garvey",
		"Gabe",
		"Gabriel",
		"Pierce",
		"Colin",
		"Damien",
		"Dawson",
		"Ben",
		"Benjamin",
		"Benjy",
		"Benny",
		"Ralph",
		"Brendan",
		"Tate",
		"Tait",
		"Rick",
		"Rickie",
		"Ricky",
		"Garrett",
		"Cole",
		"Kole",
		"Connor",
		"Indigo",
		"Humps",
		"Humphry",
		"Slade",
		"Merle",
		"Merlin",
		"Aidan",
		"Jordan",
		"Chase",
		"Eric",
		"Erik",
		"Mitch",
		"Mitchell",
		"Eddy",
		"Ed",
		"Edison",
		"Aaren",
		"Rocky",
		"Denton",
		"Tony",
		"Don",
		"Donny",
		"Donovan",
		"Pearce",
		"Cleveland",
		"Peter",
		"Ernie",
		"Arnie",
		"Kirt",
		"Kirk",
		"Trace",
		"Gerald",

	}

	FEMALE_NAMES = {
		"Jaquie",
		"Jaya",
		"Peyton",
		"Trinitie",
		"Annabelle",
		"Sydney",
		"Maddy",
		"Jennie",
		"Stacy",
		"Moriah",
		"Jezebelle",
		"Star",
		"Kara",
		"Elizabeth",
		"Sophie",
		"Justice",
		"Lorna",
		"Cherise",
		"Anastasia",
		"Tabatha",
		"Muriel",
		"Hayden",
		"Madlyn",
		"Ebony",
		"Arleen",
		"Sharen",
		"Aniston",
		"Alyx",
		"Alexandra",
		"Brandi",
		"Christie",
		"Kristen",
		"Dianne",
		"Emily",
		"Erin",
		"Emma",
		"Elle",
		"Jenna",
		"Grace",
		"Halle",
		"Haley",
		"Kaele",
		"Keandra",
		"Kimber",
		"Kyra",
		"Lauren",
		"Alexis",
		"Mary",
		"Maria",
		"Olivia",
		"Paula",
		"Portia",
		"Sammie",
		"Sallie",
		"Saige",
		"Sissy",
		"Toni",
		"Amanda",
		"Sabrina",
		"Jasmine",
		"Jazleen",
		"Jessica",
		"Roxanne",
		"Roxi",
		"Mercy",
		"Shelby",
		"Shanna",
		"Helen",
		"Eleanor",
		"Sybil",
		"Kimberly",
		"Nicole",
		"Adriana",
		"Athalia",
		"Scarlett",
		"Brianna",
		"Lydia",
		"Dolores",
		"Myrtle",
		"Florence",
		"Dinah",
		"Abby",
		"Candice",
		"Shirley",
		"Eden",
		"Keely",
		"Felicia",
		"Leyla",
		"Lila",
		"Lily",
		"Nova",
		"Casy",
		"Tulip",
		"Cecilia",
		"Beverly",
		"Arabella",
		"Bella",
		"Karina",
		"Louise",
		"Talia",
		"Phoebe",
		"Roberta",
		"Jacklyn",
		"Michelle",
		"Brenda",
		"Vera",
		"Amy",
		"Jordy",
		"Virginia",
		"Ramona",
		"Corrina",
		"Paulina",
		"Patrice",
		"Anne",
		"Annie",
		"Daria",
		"Donna",
		"Nevada",
		"Isabelle",
		"Isabella",
		"Enola",
		"Yolonda",
		"Serena",
		"Selena",
		"Elaine",
		"Tabatha",
		"Becky",
		"Beccah",
		"Rebecca",
		"Tanika",
		"Tanisha",
		"LaShondra",
		"Daphne",
		"Katherine",
		"Cary",
		"Brianna",
		"Yvette",
		"Lydia",
		"Nydia",
		"Makaeh",
		"Fawn",
		"Regan", --Yes, this is a real girl's name.
		"Faye", -- :)
		"Dillion",
		"Remy",
		"Miriama",
		"Barbara",
		"Summer",
		"Hope",
		"Faith"
	}

	TEACHER_MODELS = {
		-- Male
		[1] = {
			"models/Humans/Group01/Male_01.mdl",
			"models/Humans/Group01/male_02.mdl",
			"models/Humans/Group01/male_03.mdl",
			"models/Humans/Group01/Male_04.mdl",
			"models/Humans/Group01/Male_05.mdl",
			"models/Humans/Group01/male_06.mdl",
			"models/Humans/Group01/male_07.mdl",
			"models/Humans/Group01/male_09.mdl",
		},
		-- Female
		[2] = {
			"models/Humans/Group01/Female_01.mdl",
			"models/Humans/Group01/Female_02.mdl",
			"models/Humans/Group01/Female_03.mdl",
			"models/Humans/Group01/Female_04.mdl",
			"models/Humans/Group01/Female_06.mdl",
			"models/Humans/Group01/Female_07.mdl",
		},
	}

	TEACHERS = {
		[1] = {
			["Title"] = GetTString("Math") .. " " .. GetTString("Teacher"),
		},
		[2] = {
			["Title"] = GetTString("Math") .. " " .. GetTString("Teacher"),
		},
		[3] = {
			["Title"] = GetTString("Science") .. " " .. GetTString("Teacher"),
		},
		[4] = {
			["Title"] = GetTString("Science") .. " " .. GetTString("Teacher"),
		},
		[5] = {
			["Title"] = GetTString("English") .. " " .. GetTString("Teacher"),
		},
		[6] = {
			["Title"] = GetTString("English") .. " " .. GetTString("Teacher"),
		},
		[7] = {
			["Title"] = GetTString("Social Studies") .. " " .. GetTString("Teacher"),
		},
		[8] = {
			["Title"] = GetTString("Social Studies") .. " " .. GetTString("Teacher"),
		},
		[9] = {
			["Title"] = GetTString("Math") .. " " .. GetTString("Teacher"),
		},
		[10] = {
			["Title"] = GetTString("CompSci") .. " " .. GetTString("Teacher"),
		},
	}

	for k,v in pairs(TEACHERS) do
		local gender = math.random(1,2)

		v.Name = TEACHER_NAMES[math.random(#TEACHER_NAMES)]
		v.Model = TEACHER_MODELS[gender][math.random(#TEACHER_MODELS[gender])]

		if gender == 1 then
			v.Name = GetTString("Mr.") .. " " .. v.Name
		else
			v.Name = GetTString("Ms.") .. " " .. v.Name
		end

	end
end

CLASSES = {
	["Lunch"] = {
		["Room"] = "Cafe",
		["Subject"] = GetTString("Lunch"),
		["Name"] = GetTString("Lunch"),
	},
	["PreAlgerbra"] = {
		["Room"] = "B107",
		["Subject"] = GetTString("Math"),
		["Name"] = GetTString("Pre-Algerbra"),
	},
	["AlgerbraI"] = {
		["Room"] = "A01",
		["Subject"] = GetTString("Math"),
		["Name"] = GetTString("Algerbra I"),
	},
	["AlgerbraII"] = {
		["Room"] = "A01",
		["Subject"] = GetTString("Math"),
		["Name"] = GetTString("Algerbra II"),
	},
	["Geometry"] = {
		["Room"] = "A02",
		["Subject"] = GetTString("Math"),
		["Name"] = GetTString("Geometry"),
	},
	["PreCalculus"] = {
		["Room"] = "A02",
		["Subject"] = GetTString("Math"),
		["Name"] = GetTString("PreCalculus"),
	},

	["BiologyI"] = {
		["Room"] = "B101",
		["Subject"] = GetTString("Science"),
		["Name"] = GetTString("Biology I"),
	},
	["ChemistryI"] = {
		["Room"] = "B103",
		["Subject"] = GetTString("Science"),
		["Name"] = GetTString("Chemistry I"),
	},
	["PhysicsI"] = {
		["Room"] = "B101",
		["Subject"] = GetTString("Science"),
		["Name"] = GetTString("Physics I"),
	},
	["EarthScienceI"] = {
		["Room"] = "B103",
		["Subject"] = GetTString("Science"),
		["Name"] = GetTString("Earth Science I"),
	},

	["English9"] = {
		["Room"] = "B106",
		["Subject"] = GetTString("English"),
		["Name"] = GetTString("English 9"),
	},
	["English10"] = {
		["Room"] = "B106",
		["Subject"] = GetTString("English"),
		["Name"] = GetTString("English 10"),
	},
	["English11"] = {
		["Room"] = "B102",
		["Subject"] = GetTString("English"),
		["Name"] = GetTString("English 11"),
	},
	["English12"] = {
		["Room"] = "B102",
		["Subject"] = GetTString("English"),
		["Name"] = GetTString("English 12"),
	},

	["WorldHistory"] = {
		["Room"] = "C202",
		["Subject"] = GetTString("Social Studies"),
		["Name"] = GetTString("World History"),
	},
	["AmericanHistory"] = {
		["Room"] = "C202",
		["Subject"] = GetTString("Social Studies"),
		["Name"] = GetTString("American History"),
	},
	["Government"] = {
		["Room"] = "C204",
		["Subject"] = GetTString("Social Studies"),
		["Name"] = GetTString("Government"),
	},
	["Sociology"] = {
		["Room"] = "C204",
		["Subject"] = GetTString("Social Studies"),
		["Name"] = GetTString("Sociology"),
	},

	["ComputerScienceIA"] = {
		["Room"] = "ComputerLab1",
		["Subject"] = GetTString("Science"),
		["Name"] = GetTString("Computer Science I"),
	},
	["ComputerScienceIB"] = {
		["Room"] = "ComputerLab2",
		["Subject"] = GetTString("Science"),
		["Name"] = GetTString("Computer Science I"),
	},
}

SCHEDULE = {
	[1] = {
		[1] = "AlgerbraI", [2] = "Geometry", [9] = "PreAlgerbra",
		[3] = "PhysicsI", [4] = "ChemistryI", [10] = "ComputerScienceIA",
	},
	[2] = {
		[1] = "AlgerbraII", [2] = "PreCalculus",
		[3] = "BiologyI", [4] = "EarthScienceI", [10] = "ComputerScienceIB",
	},
	[3] = {
		[-1] = true
	},
	[4] = {
		[7] = "AmericanHistory", [8] = "Sociology",
		[5] = "English9", [6] = "English11",
	},
	[5] = {
		[7] = "WorldHistory", [8] = "Government",
		[5] = "English10", [6] = "English12",
	},
}

POSSIBLE_SCHEDULES = {
	[9] = {
		[1] = {"AlgerbraI", "PreAlgerbra"},
		[2] = {"PhysicsI", "ChemistryI", "ComputerScienceIB"},
		[3] = {"Lunch"},
		[4] = {"English9"},
		[5] = {"WorldHistory", "Government"},
	},
	[10] = {
		[1] = {"PhysicsI", "ChemistryI", "ComputerScienceIA"},
		[2] = {"AlgerbraII"},
		[3] = {"Lunch"},
		[4] = {"AmericanHistory", "Sociology"},
		[5] = {"English10"},
	},
	[11] = {
		[1] = {"Geometry"},
		[2] = {"BiologyI", "EarthScienceI", "ComputerScienceIB"},
		[3] = {"Lunch"},
		[4] = {"English11"},
		[5] = {"WorldHistory", "Government"},
	},
	[12] = {
		[1] = {"PhysicsI", "ChemistryI", "ComputerScienceIA"},
		[2] = {"PreCalculus"},
		[3] = {"Lunch"},
		[4] = {"AmericanHistory", "Sociology"},
		[5] = {"English12"},
	},
}

function GenerateSchedule(grade)
	local sch = {}
	local possibleSchs = POSSIBLE_SCHEDULES[grade]

	for i=1,NumberOfPeriods do
		sch[i] = possibleSchs[i][math.random(#possibleSchs[i])]
	end

	return sch
end
